CREATE TABLE vehicle.airliners (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    model ENUM('AMERICAN_AIRLINES_B727_200', 'EMBRAER_LINEAGE_1000E', 'AIRBUS_A310_LUFTHANSA') NOT NULL,
    color ENUM('WHITE', 'GREEN', 'BLUE', 'GREY', 'BLACK', 'RED', 'YELLOW', 'PURPLE') NOT NULL,
    max_capacity INT NOT NULL
);